// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenAdm.Data.Context;

#nullable disable

namespace OpenAdm.Data.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422231246_EmailParceiroMigration")]
    partial class EmailParceiroMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenAdm.Domain.Entities.AcessoEcommerce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DataDeCriacao");

                    b.HasIndex("ParceiroId");

                    b.ToTable("AcessosEcommerce");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.Banner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Numero"));

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.ConfiguracaoDeFrete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CepOrigem")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("CobrarCnpj")
                        .HasColumnType("boolean");

                    b.Property<bool>("CobrarCpf")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.ToTable("ConfiguracoesDeFrete");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.ConfiguracaoDePagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("CobrarCnpj")
                        .HasColumnType("boolean");

                    b.Property<bool>("CobrarCpf")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UrlWebHook")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.ToTable("ConfiguracoesDePagamento");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.ConfiguracoesDePedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailDeEnvio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PedidoMinimoAtacado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("PedidoMinimoVarejo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("VendaDeProdutoComEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.ToTable("ConfiguracoesDePedidos");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.EnderecoParceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId")
                        .IsUnique();

                    b.ToTable("EnderecoParceiro");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.HasIndex("Email", "ParceiroId")
                        .IsUnique();

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.LojaParceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contato")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NomeFoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.ToTable("LojasParceiras");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.EmpresaOpenAdm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Numero"));

                    b.Property<int>("TipoParcelaCobranca")
                        .HasColumnType("integer");

                    b.Property<string>("UrlAdmin")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("UrlEcommerce")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("TipoParcelaCobranca");

                    b.HasIndex("UrlAdmin");

                    b.HasIndex("UrlEcommerce");

                    b.HasIndex("UrlAdmin", "UrlEcommerce")
                        .IsUnique();

                    b.HasIndex("UrlAdmin", "UrlEcommerce", "Ativo");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.EventoAplicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Dados")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaOpenAdmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<short>("QuantidadeDeTentativa")
                        .HasColumnType("smallint");

                    b.Property<int>("TipoEventoAplicacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaOpenAdmId");

                    b.HasIndex("QuantidadeDeTentativa", "Finalizado");

                    b.ToTable("EventosAplicacao");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.ParcelaCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoCobranca")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataDePagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaOpenAdmId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdExterno")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MesCobranca")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("TipoParcelaCobranca")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaOpenAdmId", "AnoCobranca", "MesCobranca");

                    b.HasIndex("EmpresaOpenAdmId", "AnoCobranca", "MesCobranca", "Numero")
                        .IsUnique();

                    b.ToTable("ParcelasCobrancas");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.RedeSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Numero"));

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<int>("RedeSocialEnum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId");

                    b.ToTable("RedesSociais");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.TelefoneParceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId");

                    b.ToTable("TelefonesParceiro");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.Parceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmpresaOpenAdmId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Numero"));

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaOpenAdmId");

                    b.ToTable("Parceiros");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.TopUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataDeAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataDeCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ParceiroId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCompra")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TotalPedidos")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("ParceiroId");

                    b.ToTable("TopUsuarios");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.EnderecoParceiro", b =>
                {
                    b.HasOne("OpenAdm.Domain.Entities.Parceiro", "Parceiro")
                        .WithOne("EnderecoParceiro")
                        .HasForeignKey("OpenAdm.Domain.Entities.EnderecoParceiro", "ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.EventoAplicacao", b =>
                {
                    b.HasOne("OpenAdm.Domain.Entities.OpenAdm.EmpresaOpenAdm", "EmpresaOpenAdm")
                        .WithMany()
                        .HasForeignKey("EmpresaOpenAdmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaOpenAdm");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.ParcelaCobranca", b =>
                {
                    b.HasOne("OpenAdm.Domain.Entities.OpenAdm.EmpresaOpenAdm", "EmpresaOpenAdm")
                        .WithMany()
                        .HasForeignKey("EmpresaOpenAdmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpresaOpenAdm");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.RedeSocial", b =>
                {
                    b.HasOne("OpenAdm.Domain.Entities.Parceiro", "Parceiro")
                        .WithMany("RedesSociais")
                        .HasForeignKey("ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.OpenAdm.TelefoneParceiro", b =>
                {
                    b.HasOne("OpenAdm.Domain.Entities.Parceiro", "Parceiro")
                        .WithMany("Telefones")
                        .HasForeignKey("ParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.Parceiro", b =>
                {
                    b.HasOne("OpenAdm.Domain.Entities.OpenAdm.EmpresaOpenAdm", "EmpresaOpenAdm")
                        .WithMany()
                        .HasForeignKey("EmpresaOpenAdmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaOpenAdm");
                });

            modelBuilder.Entity("OpenAdm.Domain.Entities.Parceiro", b =>
                {
                    b.Navigation("EnderecoParceiro");

                    b.Navigation("RedesSociais");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
